//
//  MerkelMain.hpp
//  Merklerex
//
//  Created by Shivam Maheshwari on 22/04/21.
//  Copyright © 2021 Shivam Maheshwari. All rights reserved.
//

#ifndef MerkelMain_hpp
#define MerkelMain_hpp

#include <stdio.h>
#include <vector>
#include "OrderBookEntry.hpp"
#include "OrderBook.hpp"
#include "Wallet.hpp"
#include "Logger.hpp"
#include "CSVReader.hpp"

class MerkelMain {
public:
    MerkelMain();
    /** call this to start the sim */
    void init(bool bot);
    
private:
    /** prints the menu*/
    void printMenu();
    /** get the user options */
    int getUserOption();
    /** print help */
    void printHelp();
    /** print market stats */
    void printMarketStats();
    /** takes the user ask input */
    void enterAsk();
    /** takes the user bid input */
    void enterBid();
    /** print wallet */
    void printWallet();
    /** process user option choosen by user */
    void processUserOption(int userOption);
    
    Wallet wallet;
    Logger logger;

protected:
    // naming these as protected because they need to be accessed by TradingBot class.
    
    /** initialized orderbook */
    OrderBook orderbook{"20200601.csv"};
    /** current time */
    std::string currentTime;
    /** moving to the next time frame */
    void gotoNextTimeframe();
    /** process user option choosen by user */
    void withdrawOffers(std::string timestamp);
    /** make ask generated by the bot to the exchange */
    void makeAsk(OrderBookEntry& obe);
    /** make bid generated by the bot to the exchange */
    void makeBid(OrderBookEntry& obe);

};

#endif /* MerkelMain_hpp */
